<?xml version="1.0"?>
  <!DOCTYPE application [
  <!ELEMENT application (information,courses,transfercourses,exam,totalhours,signatures)>
  <!ELEMENT information (name,utcid,address,address?,phone,degreetype,major,concentration,graduationdate,utcemail)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT utcid (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ATTLIST address line (1|2) "1">
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT degreetype (#PCDATA)>
  <!ATTLIST degreetype type (Master|Specialist|Doctor) #REQUIRED>
  <!ELEMENT major (#PCDATA)>
  <!ELEMENT concentration (#PCDATA)>
  <!ELEMENT graduationdate (#PCDATA)>
  <!ELEMENT utcemail (#PCDATA)>
  <!ELEMENT courses (course*)>
  <!ELEMENT course EMPTY>
  <!ATTLIST course term CDATA "">
  <!ATTLIST course hours CDATA "">
  <!ATTLIST course grade CDATA "">
  <!ATTLIST course department CDATA "">
  <!ATTLIST course course CDATA "">
  <!ATTLIST course title CDATA "">
  <!ELEMENT transfercourses (course*)>
  <!ELEMENT exam EMPTY>
  <!ATTLIST exam required (Yes|No) "Yes">
  <!ELEMENT totalhours (#PCDATA)>
  <!ELEMENT signatures (sig*)>
  <!ELEMENT sig (#PCDATA)>
  <!ATTLIST sig type (applicant|advisor|director|dean) #IMPLIED>
  <!ATTLIST sig date CDATA #IMPLIED>
]>
<application>
  <information>
    <name>Ryan Mauldin</name>
    <utcid>bwh398</utcid>
    <address line="3834 Cambridge Ln."/>
    <address line=""/>
    <phone>423-476-4214</phone>
    <degreetype type="Master"/>
    <major>Science</major>
    <concentration>Computer Science</concentration>
    <graduationdate>12/15/2007</graduationdate>
    <utcemail>Ryan-Mauldin@utc.edu</utcemail>
  </information>
  <courses>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
  </courses>
  <transfercourses>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
    <course term="Fall 07" hours="3" grade="A" department="CPSC" course="542" title="Structured Data Exchange"/>
  </transfercourses>
  <exam required="no"/>
  <totalhours>30</totalhours>
  <signatures>
    <sig type="applicant" date=""/>
    <sig type="advisor" date=""/>
    <sig type="director" date=""/>
    <sig type="dean" date=""/>
  </signatures>
</application>