<?xml version="1.0"?>
  <!DOCTYPE application [
  <!ELEMENT application (information,courses,transfercourses,exam,totalhours,signatures)>
  <!ELEMENT information (name,utcid,address,address?,phone,degreetype,major,concentration,graduationdate,utcemail)>
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT utcid (#PCDATA)>
  <!ELEMENT address (#PCDATA)>
  <!ATTLIST address line (1|2) "1">
  <!ELEMENT phone (#PCDATA)>
  <!ELEMENT degreetype (#PCDATA)>
  <!ATTLIST degreetype type (Master|Specialist|Doctor) #REQUIRED>
  <!ELEMENT major (#PCDATA)>
  <!ELEMENT concentration (#PCDATA)>
  <!ELEMENT graduationdate (#PCDATA)>
  <!ELEMENT utcemail (#PCDATA)>
  <!ELEMENT courses (course*)>
  <!ELEMENT course EMPTY>
  <!ATTLIST course term CDATA "">
  <!ATTLIST course hours CDATA "">
  <!ATTLIST course grade CDATA "">
  <!ATTLIST course department CDATA "">
  <!ATTLIST course course CDATA "">
  <!ATTLIST course title CDATA "">
  <!ELEMENT transfercourses (course*)>
  <!ELEMENT exam EMPTY>
  <!ATTLIST exam required (yes|no) "yes">
  <!ELEMENT totalhours (#PCDATA)>
  <!ELEMENT signatures (sig*)>
  <!ELEMENT sig (#PCDATA)>
  <!ATTLIST sig type (applicant|advisor|director|dean) #IMPLIED>
  <!ATTLIST sig date CDATA #IMPLIED>
]>
<application>
  <information>
    <name>Sumit Khanna</name>
    <utcid>kbv855</utcid>
    <address line="1">123 Some Street</address>
    <address line="2">Apt C</address>
    <phone>555-555-5555</phone>
    <degreetype type="Master"/>
    <major>Computer Science</major>
    <concentration>none</concentration>
    <graduationdate>Summer 2007</graduationdate>
    <utcemail>Sumit-nospam-Khanna00@utc.edu</utcemail>
  </information>
  <courses>
    <course term="Summer 2005" hours="3" grade="3.0" department="CPSC" course="544" title="Computer Network Security"/>
    <course term="Fall 2005" hours="3" grade="3.0" department="CPSC" course="533" title="Advanced Compuer Arch"/>
    <course term="Fall 2005" hours="3" grade="3.0" department="CPSC" course="550" title="Combination and Graphy Theory"/>
    <course term="Spring 2006" hours="3" grade="3.0" department="CPSC" course="532" title="Advanced Topics in System Software"/>
    <course term="Spring 2006" hours="3" grade="3.0" department="CPSC" course="538" title="Real-time Emb Systems"/>
  </courses>
  <transfercourses>
    <course term="" hours="" grade="" department="" course="" title=""/>
    <course term="" hours="" grade="" department="" course="" title=""/>
    <course term="" hours="" grade="" department="" course="" title=""/>
    <course term="" hours="" grade="" department="" course="" title=""/>
    <course term="" hours="" grade="" department="" course="" title=""/>
  </transfercourses>
  <exam required="no"/>
  <totalhours>15</totalhours>
  <signatures>
    <sig type="applicant" date=""/>
    <sig type="advisor" date=""/>
    <sig type="director" date=""/>
    <sig type="dean" date=""/>
  </signatures>
</application>
